name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify Vercel secrets
      run: |
        if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "🚨 ERROR: VERCEL_TOKEN secret is not configured"
          echo "📚 Please see .github/VERCEL_TROUBLESHOOTING.md for setup instructions"
          exit 1
        fi
        if [ -z "${{ secrets.PROJECT_ID }}" ]; then
          echo "🚨 ERROR: PROJECT_ID secret is not configured" 
          exit 1
        fi
        if [ -z "${{ secrets.ORG_ID }}" ]; then
          echo "🚨 ERROR: ORG_ID secret is not configured"
          exit 1
        fi
        echo "✅ All Vercel secrets are configured"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build --workspace=frontend
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:8000' }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co' }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-key' }}
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./frontend
        github-comment: true
        github-deployment: false
